runtime: python37

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto

resources:
  cpu: 2
  memory_gb: 2.3
  disk_size_gb: 10
  volumes:
  - name: ramdisk1
    volume_type: tmpfs
    size_gb: 0.5